#!/bin/bash

dpref=("sda" "mmb" "nvme")

for p in "${dpref[@]}"
do
    df -h | grep $p |\
        sed -e "s_/dev/$p[1-9]_\x1b[34m&\x1b[0m_" |\
        sed -e "s_9[0-9]%_\x1b[31m&\x1b[0m_" |\
        sed -e "s_/mnt/[-_A-Za-z0-9]*_\x1b[34;1m&\x1b[0m_"
done
