#!/bin/bash
#
# (c) 2017 iomonad <clement@trosa.io>
#
# Description: Fetch status of RATP
# traffic and display perturbations
#

curl -sX GET "https://api-ratp.pierre-grimaud.fr/v4/traffic/metros" \
     -H  "accept: application/json" \
    | jq '.result.metros[] | select(.slug!="normal")' \
    | jq -r '"----\nLigne \(.line): (\(.slug)): \(.message)\n----\n"'
